- name: Create necessary directories
  file:
    path: /etc/nginx/conf.d/
    state: directory

- name: Nginx configuration
  ansible.builtin.copy:
    src: ./load-balancer.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0744'
    backup: yes

- name: Nginx restart
  service:
    name: nginx
    state: started
    enabled: yes
